{% set name = "dholth_test_package" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests

test:
  imports:
    - dtp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dholth/dholth-test-package
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dholth
